name: TruffleHog Secret Scan

on:
  pull_request:
    branches:
      - main  # Adjust to match your default/main branch

permissions:
  contents: read
  pull-requests: read  # Required to fetch changed files

jobs:
  trufflehog_scan:
    name: Secret Scan with TruffleHog
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensures we have enough history to compare changes

      - name: Get Changed Files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | tr '\n' ' ')
          echo "Changed files: $CHANGED_FILES"
          echo "FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Install TruffleHog
        run: |
          pip install trufflehog

      - name: Run TruffleHog on Changed Files
        run: |
          if [[ -z "$FILES" ]]; then
            echo "No changed files to scan."
            exit 0
          fi
          trufflehog filesystem --path $FILES || echo "Secrets detected!"
