name: TruffleHog Scan on PR Changes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  trufflehog_scan:
    name: Scan Changed Files for Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensures we get previous commit for diff

      - name: Get Changed Files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Install TruffleHog
        run: |
          pip install trufflehog

      - name: Scan Changed Files
        run: |
         for file in $CHANGED_FILES; do
         if [[ -f "$file" ]]; then
         echo "Scanning $file"
         trufflehog filesystem --path "$file" --entropy=True || true
         fi
         done

