name: Secret Scan with TruffleHog

on:
  pull_request:
    branches:
      - main  # Adjust based on your default branch

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch limited history to reduce network usage

      - name: Ensure full history for git diff
        run: |
          if git rev-parse --is-shallow-repository; then
            git fetch --prune --unshallow
          else
            git fetch --prune
          fi

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          echo "Changed files: $CHANGED_FILES"
          echo "FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog on changed files
        run: |
          if [ -n "$FILES" ]; then
            echo "Scanning changed files..."
            trufflehog filesystem --no-history $FILES
          else
            echo "No changed files detected."
          fi
