name: TruffleHog Secret Scan

on:
  pull_request:
    branches:
      - main  # Change as needed

permissions:
  contents: read
  pull-requests: read

jobs:
  trufflehog_scan:
    name: Secret Scan with TruffleHog
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
  uses: actions/checkout@v4
  with:
    fetch-depth: 0  # Fetch full history, including branches

      - name: Fetch base branch
        run: |
    git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1


      - name: Get Changed Files
        id: changed-files
        run: |
         BASE_BRANCH=${{ github.event.pull_request.base.ref }}
         CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH HEAD)
         echo "Changed files: $CHANGED_FILES"
         echo "FILES=$CHANGED_FILES" >> $GITHUB_ENV


      - name: Install TruffleHog
        run: |
          pip install trufflehog

      - name: Run TruffleHog on Changed Files
        run: |
          if [[ -z "$FILES" ]]; then
            echo "No changed files to scan."
            exit 0
          fi
          
          echo "Scanning changed files: $FILES"
          for file in $FILES; do
            echo "Scanning $file..."
            trufflehog filesystem --path "$file" || FOUND=true
          done

          if [[ "$FOUND" == "true" ]]; then
            echo "⚠️ Secrets detected!"
            exit 1
          fi
